### ISSUE TITLE
debugging -crossplay for valheim_server from arm64 vm

### ISSUE THREAD

**Issue by bitdo1** [husjon/husjon#2]
I am trying to get xbox support for the [Valheim server](https://gist.github.com/husjon/c5225997eb9798d38db9f2fca98891ef) that runs from an arm64 host.   From searching the web `libparty.so` seems to be the key to getting this to work.  According to this [reddit post](https://www.reddit.com/r/valheim/comments/11sd38v/raspberry_pi_dedicated_server_with_crossplay/) some people got this to work from a raspberry pi which is also arm64.

Modifications to setup script:
- Disabled the arm64 check to allow enabling the `-crossplay` option
- Set the `BOX64_VERSION="main"` to pickup the latest fixes from box64
- Added `Environment=BOX64_LOG=1` to the systemd script to get a little bit more debug info.

First I got errors for libpulse not found.  I ran `sudo apt install libpulse0 libpulse-dev`.  Now it gets errors for `libpulse-mainloop-glib.so.0`.  This library is already installed with those packages.  I ran an `strace` to figure out what it is trying to open since the missing library seems to exist.  I found its trying to open an x86_64 version of libpulse-mainloop-glib.so.0 and I'm not sure how to install that or if it even makes sense to install it. 

Any advice on what to try next?

Console output:
```
Using emulated /home/ubuntu/valheim_server/valheim_server_Data/Plugins/libparty.so
Using native(wrapped) libz.so.1
Using native(wrapped) libatomic.so.1
Using native(wrapped) libpulse.so.0
Using native(wrapped) libpulse-simple.so.0
Error loading needed lib libpulse-mainloop-glib.so.0
Using emulated /lib/x86_64-linux-gnu/libstdc++.so.6
Error loading one of needed lib
Error initializing needed lib /home/ubuntu/valheim_server/valheim_server_Data/Plugins/libparty.so
```

strace:
```
write(1, "Using native(wrapped) libpulse-s"..., 43) = 43
getcwd("/home/ubuntu/valheim_server", 1024) = 28
readlinkat(AT_FDCWD, "/home/ubuntu/valheim_server/libpulse-mainloop-glib.so.0", 0xfffffa0d4eb0, 1023) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "libpulse-mainloop-glib.so.0", O_RDONLY) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "/home/ubuntu/valheim_server/libpulse-mainloop-glib.so.0", O_RDONLY) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "/home/ubuntu/valheim_server/x86_64/libpulse-mainloop-glib.so.0", O_RDONLY) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "./linux64/libpulse-mainloop-glib.so.0", O_RDONLY) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "./linux64/x86_64/libpulse-mainloop-glib.so.0", O_RDONLY) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "./libpulse-mainloop-glib.so.0", O_RDONLY) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "./x86_64/libpulse-mainloop-glib.so.0", O_RDONLY) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "lib/libpulse-mainloop-glib.so.0", O_RDONLY) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "lib/x86_64/libpulse-mainloop-glib.so.0", O_RDONLY) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "lib64/libpulse-mainloop-glib.so.0", O_RDONLY) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "lib64/x86_64/libpulse-mainloop-glib.so.0", O_RDONLY) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "x86_64/libpulse-mainloop-glib.so.0", O_RDONLY) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "x86_64/x86_64/libpulse-mainloop-glib.so.0", O_RDONLY) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "bin64/libpulse-mainloop-glib.so.0", O_RDONLY) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "bin64/x86_64/libpulse-mainloop-glib.so.0", O_RDONLY) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "libs64/libpulse-mainloop-glib.so.0", O_RDONLY) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "libs64/x86_64/libpulse-mainloop-glib.so.0", O_RDONLY) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "/lib/x86_64-linux-gnu/libpulse-mainloop-glib.so.0", O_RDONLY) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "/lib/x86_64-linux-gnu/x86_64/libpulse-mainloop-glib.so.0", O_RDONLY) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "/usr/lib/x86_64-linux-gnu/libpulse-mainloop-glib.so.0", O_RDONLY) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "/usr/lib/x86_64-linux-gnu/x86_64/libpulse-mainloop-glib.so.0", O_RDONLY) = -1 ENOENT (No such file or directory)
write(1, "Error loading needed lib libpuls"..., 53) = 53
```

**Comment by husjon** [comment]
Hmm, I think the error loading `libpulse-mainloop-glib.so.0` comes down to box64 not being able to wrap it, hence it's trying to load x86_64 version of it.

You might have some luck trying to create an issue with [Box64](https://github.com/ptitSeb/box64) with your findings, the project owner might able to give some kind of estimate as to what would be needed.
If you do, please drop the issue link here so I can keep an eye as well. :)

**Comment by bitdo1** [comment]
I found this comment about this same library on the box64 project:

https://github.com/ptitSeb/box64/issues/115#issuecomment-1272327530

I should try what was suggested there, get a x86_64 version of that library, before opening an issue.

**Comment by husjon** [comment]
I see ptitSeb commented about wrapping the library being the fix.
I have no idea how much work it is for them, but it will be pretty interesting to see. :+1:

**Comment by bitdo1** [comment]
Using ptitSeb's advice I got an xbox to connect.  I got an x86_64 copy of `libpulse-mainloop-glib.so.0` from https://packages.ubuntu.com/jammy/amd64/libpulse-mainloop-glib0/download and put it in the `valheim_server/linux64` folder and started the server with `-crossplay`.  It took a while for the server to print out the following.  It did a couple playfab retries and then:
```
Joined PlayFab Party network with ID ...
Created PlayFab lobby with ID...
Session "xxxxxxx" with join code xxxxxx and IP xxx.xxx.xxx.xxx:2456 is active with 0 player(s)
```
Then connecting from xbox worked.  I could refresh the server I had already typed in and it switched from red x to another icon and I could connect, prompted for password and the game loaded in.  Other than connecting I don't have time to test using it right now.  Hopefully its stable.

**Comment by husjon** [comment]
Brilliant work and please do keep me updated after you'd have the time to test it some more.

I could create a section for it in the guide in the next couple of days although mark it as highly experimental until further testing has been made.

**Comment by husjon** [comment]
I was playing around with multiarch to see if I was able to pull in the x86_64 library.
However thinking of the guide or more specifically the install script, also adding onto it the wrapping being considered by ptitSeb, I think for now just pulling down the archive directly and extracting `libpulse-mainloop-glib0.so.0` into valheim_server is a slightly easier way of doing it as we do not need any other libraries (hopefully) :)

On another note I pulled down the archive and added it and found it kind of surprising how few errors were thrown.
Also, it seem like the only hard requirement is `libpulse0` other than `libpulse-mainloop-glib0` (`libpulse-dev` seem to not be needed)

And here it is showing up in the community listings after a little bit of waiting
![image](https://github.com/husjon/husjon/assets/554229/bd20d4f3-c150-4f6d-9806-007547feed04)

I do not have Valheim on Xbox or know of anyone that do, however this is looking good so far.

If you're able to test it a bit with an Xbox I will definitely open this up to the rest.

**Comment by bitdo1** [comment]
It worked well for the hour or two I spent on it last night.   Its probably good enough to let more people kick the tires.  Is hard coding it to that download link good enough?  I ended up extracting the deb into a folder and then making a link to the library:
```
$ ls -la valheim_server/linux64/
total 34712
drwxrwxr-x 2 ubuntu ubuntu     4096 Aug  3 16:46 .
drwxrwxr-x 6 ubuntu ubuntu     4096 Aug  1 20:43 ..
lrwxrwxrwx 1 ubuntu ubuntu       76 Aug  3 16:46 libpulse-mainloop-glib.so.0 -> /home/ubuntu/debug-work/usr/lib/x86_64-linux-gnu/libpulse-mainloop-glib.so.0
-rwxrwxr-x 1 ubuntu ubuntu 35532192 Jul 31 18:17 steamclient.so

$ ls -la debug-work/usr/lib/x86_64-linux-gnu/
total 28
drwxr-xr-x 2 ubuntu ubuntu  4096 Aug  3 16:43 .
drwxr-xr-x 3 ubuntu ubuntu  4096 Feb 24  2022 ..
lrwxrwxrwx 1 ubuntu ubuntu    31 Feb 24  2022 libpulse-mainloop-glib.so.0 -> libpulse-mainloop-glib.so.0.0.6
-rw-r--r-- 1 ubuntu ubuntu 18576 Feb 24  2022 libpulse-mainloop-glib.so.0.0.6
```

There is probably a smarter way to just extract `libpulse-mainloop-glib.so.0.0.6` directly to `valheim_server/linux64` and then create the soft link named `libpulse-mainloop-glib.so.0`.

**Comment by husjon** [comment]
Nice and yeah I agree it seem stable enough to let more people start testing it.

To expand on the multiarch testing, it seem that the dependency chain to just get `libpulse-mainloop-glib.so.0:amd64` it would need a lot more amd64 (x86_64) packages making it unfeasible in the long run.

What I've been experimenting with so far has been to just download and extract the deb package to `/tmp`, then copying the library `libpulse-mainloop-glib.so.0` directly to `~/valheim_server/linux64`.

I'm considering making it switchable based on if you want crossplay or not, so that:
* if you want crossplay, it will download and add the library file if it doen't exist already
* if not, if the file exist it will remove it.

Here's the installation section of the installer for reference:
```bash
    # Add x86_64 version of libpulse-mainloop-glib.so.0
    if [[ $CROSSPLAY_SUPPORT == true ]]; then
        if [[ ! -f ~/valheim_server/linux64/libpulse-mainloop-glib.so.0 ]]; then
            info "Installing libpulse-mainloop-glib.so.0:x86_64"
            pushd "$(mktemp -d)"
            wget http://mirrors.kernel.org/ubuntu/pool/main/p/pulseaudio/libpulse-mainloop-glib0_15.99.1+dfsg1-1ubuntu1_amd64.deb
            ar x libpulse-mainloop-glib0_15.99.1+dfsg1-1ubuntu1_amd64.deb && \
                zstd -d data.tar.zst && \
                tar xf data.tar
            cp usr/lib/x86_64-linux-gnu/libpulse-mainloop-glib.so.0 "/home/$USER/valheim_server/linux64/"
            success "Installing libpulse-mainloop-glib.so.0:x86_64 - Done"
            popd
        fi
    else
        rm -f "/home/$USER/valheim_server/linux64/libpulse-mainloop-glib.so.0"
    fi
```

**Comment by husjon** [comment]
Do you by the way have a quick rundown as to how to join the server with an Xbox?
Do you f.ex need to use the join code or wait for it to show in the server listings?

Asking as I'd like to add this information to the documentation :)

**Comment by bitdo1** [comment]
I used `dpkg -x file.deb` to extract the files.  If we assume this script is always ubuntu its probably safe to use `dpkg`.

To connect to a private server from xbox, from the 'select world' dialog, you push RB (right bumper) to get to the 'Join Game' tab.  This switches you to the 'select server' dialog.  Then you click RS (right stick) to 'add server'.  Then a dialog will appear that says 'Enter IP or invite code'.  Click RS (right stick) again to pop up a virtual keyboard.  There you type in the IP address, colon, port number.  For example:  `10.20.30.40:2456` and submit that response.  I never tried the invite code method.  Then the server you provided will show up in the 'select server' dialog.  If the server is not available, or not finished connecting to the playfab stuff, then it will show with a red X icon.  You can click 'x' button to refresh the server list and it will attempt to contact the server again.  Once its available you can click on it to join.

![image](https://github.com/husjon/husjon/assets/24960519/e19d0975-e2c1-430a-873f-7ef1aea4ad73)
![image](https://github.com/husjon/husjon/assets/24960519/acd0fcf3-493e-46c5-b485-ac0b3bb660b6)
![image](https://github.com/husjon/husjon/assets/24960519/8361a004-e346-4fae-9c15-b340fb4ca947)

**Comment by husjon** [comment]
> I used `dpkg -x file.deb` to extract the files. If we assume this script is always ubuntu its probably safe to use `dpkg`.

Agree, for now the guide is Ubuntu only so I'll stick to using `dpkg`, thanks for the tip.


So the join procedure is more or less the same as on PC then, that's good.  
As for the invite code method, it's the same as using IP just less cumbersome especially for when using the controller. :)

I'll push the changes some time tomorrow.

**Comment by husjon** [comment]
I've just pushed the changed allowing more people to try it out.

Thanks for getting the ball rolling. :)

**Comment by bitdo1** [comment]
I just tried the updated script and getting my server back into a state before my modifications.   I found 2 issues.  `libpulse0` is not installed automatically and the syntax I gave you for `dpkg -x` is missing the last parameter, the destination path `./`.    So when the script ran it never extracted or copied the 64-bit library.

Applying this patch got it to work for me:
```
$ diff -u setup_valheim_server.sh setup_valheim_server.sh-fix
--- setup_valheim_server.sh     2023-08-07 17:33:01.994649560 +0000
+++ setup_valheim_server.sh-fix 2023-08-07 18:01:39.885411434 +0000
@@ -113,6 +113,7 @@
         build-essential \
         cmake \
         gcc-arm-linux-gnueabihf \
+        libpulse0 \
         libc6:armhf \
         libncurses5:armhf \
         libstdc++6:armhf && \
@@ -189,7 +190,7 @@
             info "Installing libpulse-mainloop-glib.so.0:x86_64"
             pushd "$(mktemp -d)"
             wget http://mirrors.kernel.org/ubuntu/pool/main/p/pulseaudio/libpulse-mainloop-glib0_15.99.1+dfsg1-1ubuntu1_amd64.deb
-            dpkg -x libpulse-mainloop-glib0_15.99.1+dfsg1-1ubuntu1_amd64.deb && \
+            dpkg -x libpulse-mainloop-glib0_15.99.1+dfsg1-1ubuntu1_amd64.deb ./ && \
                 cp usr/lib/x86_64-linux-gnu/libpulse-mainloop-glib.so.0 "/home/$USER/valheim_server/linux64/"
             success "Installing libpulse-mainloop-glib.so.0:x86_64 - Done"
             popd
```

**Comment by husjon** [comment]
Thanks, just pushed the changes.

**Comment by bitdo1** [comment]
works.  thank you!
